name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest'

    - name: Install dependencies
      run: bun install

    - name: Test
      run: bun test

    - name: Build
      run: bun run build

    - name: Bump version and push tag
      uses: phips28/gh-action-bump-version@master
      with:
        tag-prefix: 'v'
        version-type: minor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      run: bun publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}